authentication.profile = auth dev profile
server.port=0
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
spring.data.mongodb.uri=mongodb://localhost:27017/userdb

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

security.jwt.key.private=1f98360632c3007c8601fbf2fdf20da49e159ca54dd83fb17349ca0eab801c37
security.jwt.user.generator=AUTH0JWT-BACK