product.profile = product dev profile
server.port=8080
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
management.endpoints.web.exposure.include=*

app.prop=product prop update in MQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
